Repository shoppingflux/module-prestashop, pull requests merged in 2022-12, with the labels that each got.

#227 Fixbug: remove a discount from invoice (37710)
  classes/actions/ShoppingfeedOrderImportActions.php
Labels: bug

#228 Add token as mandatory to get product xml feed (37103)
  controllers/admin/AdminShoppingfeedGeneralSettings.php
  controllers/front/product.php
  views/templates/admin/shoppingfeed_general_settings/products_feeds.tpl
Labels: bug

#229 Using token in addition to secure_key in cron (36176)
  controllers/admin/AdminShoppingfeedProcessMonitor.php
  controllers/front/syncAll.php
Labels: enhancement

#230 Adding dni to address (37070)
  202/tests/OrderImport/OrderImportSimpleTest.php
  202/tests/OrderImport/dataset/order-amazon.json
  shoppingfeed.php
  src/OrderImport/Rules/SetDniToAddress.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: enhancement

#231 handle the new field relayId on order import (37419)
  202/docker/run_for_unittest.sh
  202/tests/OrderImport/OrderRulesColissimoTest.php
  202/tests/OrderImport/dataset/order-manomano-colissimo.json
  src/OrderImport/Rules/AbstractColissimo.php
  src/OrderImport/Rules/AbstractMondialrelay.php
  src/OrderImport/Rules/CdiscountColissimo.php
  src/OrderImport/Rules/ColizeyColissimo.php
  src/OrderImport/Rules/GaleriesLafayetteColissimo.php
  src/OrderImport/Rules/GoSportMondialrelay.php
  src/OrderImport/Rules/ManomanoColissimo.php
  src/OrderImport/Rules/ManomanoDpdRelais.php
  src/OrderImport/Rules/Mondialrelay.php
  src/OrderImport/Rules/MonechelleColissimo.php
  src/OrderImport/Rules/RelaisColisRule.php
  src/OrderImport/Rules/RueducommerceMondialrelay.php
  src/OrderImport/Rules/ZalandoColissimo.php
Labels: enhancement

#234 add marketplace reference as payement transaction ID (37799)
  202/tests/OrderImport/OrderImportSimpleTest.php
  classes/actions/ShoppingfeedOrderImportActions.php
Labels: enhancement

#235 Fix order tracking (30199)
  src/Services/OrderTracker.php
Labels: bug

#236 Order shipped by marketplace imported in error (38044)
  202/tests/OrderImport/OrderShippedByMarketplaceTest.php
  src/OrderImport/RuleAbstract.php
  src/OrderImport/Rules/ShippedByMarketplace.php
Labels: bug

#237 Release 1.9.2
  .github/SECURITY.md
  202/build.xml
  202/docker/run_for_unittest.sh
  202/tests/OrderImport/OrderImportSimpleTest.php
  202/tests/OrderImport/OrderRulesColissimoTest.php
  202/tests/OrderImport/OrderShippedByMarketplaceTest.php
  202/tests/OrderImport/dataset/order-amazon.json
  202/tests/OrderImport/dataset/order-manomano-colissimo.json
  classes/actions/ShoppingfeedOrderImportActions.php
  controllers/admin/AdminShoppingfeedGeneralSettings.php
  controllers/admin/AdminShoppingfeedProcessMonitor.php
  controllers/front/product.php
  controllers/front/syncAll.php
  shoppingfeed.php
  src/OrderImport/RuleAbstract.php
  src/OrderImport/Rules/AbstractColissimo.php
  src/OrderImport/Rules/AbstractMondialrelay.php
  src/OrderImport/Rules/CdiscountColissimo.php
  src/OrderImport/Rules/ColizeyColissimo.php
  src/OrderImport/Rules/GaleriesLafayetteColissimo.php
  src/OrderImport/Rules/GoSportMondialrelay.php
  src/OrderImport/Rules/ManomanoColissimo.php
  src/OrderImport/Rules/ManomanoDpdRelais.php
  src/OrderImport/Rules/Mondialrelay.php
  src/OrderImport/Rules/MonechelleColissimo.php
  src/OrderImport/Rules/RelaisColisRule.php
  src/OrderImport/Rules/RueducommerceMondialrelay.php
  src/OrderImport/Rules/SetDniToAddress.php
  src/OrderImport/Rules/ShippedByMarketplace.php
  src/OrderImport/Rules/ZalandoColissimo.php
  src/Services/OrderTracker.php
  translations/fr.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  views/templates/admin/shoppingfeed_general_settings/products_feeds.tpl
Labels: release

#239 Import order with token language (38247)
  202/tests/OrderImport/GaleriesLafayetteColissimoTest.php
  202/tests/OrderImport/OrderImportCDiscountTest.php
  202/tests/OrderImport/OrderImportDPDManomanopro.php
  202/tests/OrderImport/OrderImportManoManoDpdRelaisWithDoubleTaxOnProductTest.php
  202/tests/OrderImport/OrderImportMondialRelaisTest.php
  202/tests/OrderImport/OrderImportSimpleTest.php
  202/tests/OrderImport/OrderImportStockTest.php
  202/tests/OrderImport/OrderImportVerifyCurrencyTest.php
  202/tests/OrderImport/OrderImportWithConfigTest.php
  202/tests/OrderImport/OrderImportZalandoTest.php
  202/tests/OrderImport/OrderRulesAmazonManomanoTvaTest.php
  202/tests/OrderImport/OrderRulesColissimoTest.php
  202/tests/OrderImport/OrderShippedByMarketplaceTest.php
  202/tests/OrderImport/OrderSplittingTest.php
  classes/actions/ShoppingfeedOrderImportActions.php
  controllers/front/syncOrder.php
Labels: bug
