Repository shoppingflux/module-prestashop, pull requests merged in 2023-09, with the labels that each got.

#291 Compatibility for PHP 5.6 - SfTools
  shoppingfeed.php
Labels: bug

#285 Update logs in case of sync stock (41463)
  classes/actions/ShoppingfeedProductSyncStockActions.php
  translations/fr.php
Labels: bug

#287 ProductSerializer - add field 'min quantity for sale' (41039)
  202/tests/ProductSerializer/TestAttributeTestCase.php
  src/Services/ProductAttributeCombination.php
  src/Services/ProductSerializer.php
Labels: enhancement

#288 Adjust order importation date 30 rolling days (41653)
  controllers/front/syncOrder.php
Labels: enhancement

#289 Add configuration for Test order not only canceled after import (40564)
  202/tests/OrderImport/OrderRulesTestingTest.php
  src/OrderImport/Rules/TestingOrder.php
  translations/fr.php
Labels: enhancement

#286 Skip tax in case of Retif marketplace (41868)
  202/tests/OrderImport/OrderImportRetifTest.php
  src/OrderImport/Rules/SkipTax.php
Labels: bug

#293 Release 1.10.3
  202/build.xml
  202/tests/OrderImport/OrderImportRetifTest.php
  202/tests/OrderImport/OrderRulesTestingTest.php
  202/tests/ProductSerializer/TestAttributeTestCase.php
  classes/actions/ShoppingfeedProductSyncStockActions.php
  controllers/front/syncOrder.php
  shoppingfeed.php
  src/OrderImport/Rules/SkipTax.php
  src/OrderImport/Rules/TestingOrder.php
  src/Services/ProductAttributeCombination.php
  src/Services/ProductSerializer.php
  translations/fr.php
Labels: release
