Repository shoppingflux/module-prestashop, pull requests merged in 2024-07, with the labels that each got.

#347 refs #46835 syncAll uri
  controllers/admin/AdminShoppingfeedProcessMonitor.php
  controllers/front/syncAll.php
Labels: enhancement

#349 Refactoring ColissimoRule for relay pickup (46736)
  202/docker/run_for_unittest.sh
  202/tests/OrderImport/OrderImportLeroyMerlinTest.php
  202/tests/OrderImport/OrderImportManoManoDpdRelaisWithDoubleTaxOnProductTest.php
  202/tests/OrderImport/OrderImportSimpleTest.php
  202/tests/OrderImport/OrderRulesColissimoTest.php
  202/tests/OrderImport/dataset/order-galerieslafayette-colissimo.json
  202/tests/OrderImport/dataset/order-leroymerlin-colissimo.json
  202/tests/OrderImport/dataset/order-zalando.json
  shoppingfeed.php
  src/OrderImport/Rules/AbstractColissimo.php
  src/OrderImport/Rules/BhvColissimo.php
  src/OrderImport/Rules/CdiscountColissimo.php
  src/OrderImport/Rules/ColissimoRule.php
  src/OrderImport/Rules/ColizeyColissimo.php
  src/OrderImport/Rules/GaleriesLafayetteColissimo.php
  src/OrderImport/Rules/LeroyMerlinColissimo.php
  src/OrderImport/Rules/ManomanoColissimo.php
  src/OrderImport/Rules/MonechelleColissimo.php
  src/OrderImport/Rules/ShowroompriveColissimo.php
  src/OrderImport/Rules/VeepeegroupColissimo.php
  src/OrderImport/Rules/ZalandoColissimo.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_files.php
  vendor/composer/autoload_namespaces.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
Labels: enhancement

#351 Rename deprecated hook actionDeleteProductAttribute (47112)
  shoppingfeed.php
Labels: enhancement

#350 Refactor MondialrelayRule for relay pickup (46735)
  202/tests/OrderImport/OrderImportMondialRelaisTest.php
  shoppingfeed.php
  src/OrderImport/Rules/GoSportMondialrelay.php
  src/OrderImport/Rules/Mondialrelay.php
  src/OrderImport/Rules/MondialrelayRule.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: enhancement

#355 refs #46735 error fix
  src/OrderImport/Rules/MondialrelayRule.php
Labels: bug

#356 🚀 Release 1.12.0
  202/build.xml
  202/docker/run_for_unittest.sh
  202/tests/OrderImport/OrderImportLeroyMerlinTest.php
  202/tests/OrderImport/OrderImportManoManoDpdRelaisWithDoubleTaxOnProductTest.php
  202/tests/OrderImport/OrderImportMondialRelaisTest.php
  202/tests/OrderImport/OrderImportSimpleTest.php
  202/tests/OrderImport/OrderRulesColissimoTest.php
  202/tests/OrderImport/dataset/order-galerieslafayette-colissimo.json
  202/tests/OrderImport/dataset/order-leroymerlin-colissimo.json
  202/tests/OrderImport/dataset/order-zalando.json
  shoppingfeed.php
  src/OrderImport/Rules/AbstractColissimo.php
  src/OrderImport/Rules/BhvColissimo.php
  src/OrderImport/Rules/CdiscountColissimo.php
  src/OrderImport/Rules/ColissimoRule.php
  src/OrderImport/Rules/ColizeyColissimo.php
  src/OrderImport/Rules/GaleriesLafayetteColissimo.php
  src/OrderImport/Rules/GoSportMondialrelay.php
  src/OrderImport/Rules/LeroyMerlinColissimo.php
  src/OrderImport/Rules/ManomanoColissimo.php
  src/OrderImport/Rules/Mondialrelay.php
  src/OrderImport/Rules/MondialrelayRule.php
  src/OrderImport/Rules/MonechelleColissimo.php
  src/OrderImport/Rules/ShowroompriveColissimo.php
  src/OrderImport/Rules/VeepeegroupColissimo.php
  src/OrderImport/Rules/ZalandoColissimo.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_files.php
  vendor/composer/autoload_namespaces.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
Labels: release
