Repository shoppingflux/module-prestashop, pull requests merged in 2024-12, with the labels that each got.

#385 upgrade actions/cachev4
  .github/workflows/php.yml
  .github/workflows/phpunit.yml
Labels: enhancement

#387 Release 1.12.2
  .github/workflows/php.yml
  .github/workflows/phpunit.yml
  202/build.xml
  classes/ShoppingfeedApi.php
  classes/actions/ShoppingfeedOrderSyncActions.php
  classes/actions/ShoppingfeedProductSyncPreloadingActions.php
  composer.lock
  controllers/admin/AdminShoppingfeedGeneralSettings.php
  controllers/front/product.php
  shoppingfeed.php
  src/OrderImport/Rules/ColissimoRule.php
  src/Services/ProductSerializer.php
  translations/fr.php
  upgrade/install-1.12.2.php
Labels: release

#382 Tax for business orders (48623)
  202/docker/run_for_unittest.sh
  202/tests/OrderImport/OrderImportRetifTest.php
  202/tests/OrderImport/OrderImportSkipTaxTest.php
  202/tests/OrderImport/OrderRuleTaxForBusinessTest.php
  202/tests/OrderImport/dataset/order-amazon-business.json
  202/tests/OrderImport/dataset/order-business.json
  202/tests/OrderSync/OrderSyncStatusTest.php
  classes/actions/ShoppingfeedOrderImportActions.php
  controllers/admin/AdminShoppingfeedOrderImportRules.php
  shoppingfeed.php
  src/OrderImport/Rules/SkipTax.php
  src/OrderImport/Rules/TaxExclMarketplace.php
  src/OrderImport/Rules/TaxForBusiness.php
  translations/fr.php
  views/templates/admin/shoppingfeed_order_import_rules/tax-for-business-desc.tpl
Labels: enhancement

#383 Unit-test. update ps version to 8.1.5 (42405)
  202/docker/Dockerfile
  202/tests/OrderImport/OrderImportManoManoDpdRelaisWithDoubleTaxOnProductTest.php
Labels: enhancement

#380 Upload invoice (49022)
  202/build.xml
  classes/ShoppingfeedApi.php
  classes/ShoppingfeedTaskOrder.php
  classes/actions/ShoppingfeedOrderSyncActions.php
  controllers/admin/AdminShoppingfeedOrderImportRules.php
  controllers/front/syncOrder.php
  shoppingfeed.php
  src/OrderInvoiceSync/Hub.php
  src/OrderInvoiceSync/Marketplace.php
  upgrade/install-2.0.0.php
  views/templates/admin/shoppingfeed_order_import_rules/order_status_syncro.tpl
  views/templates/admin/shoppingfeed_order_import_rules/order_status_syncro_178.tpl
Labels: enhancement

#364 Send notification option (43794)
  classes/actions/ShoppingfeedOrderImportActions.php
  controllers/admin/AdminShoppingfeedOrderImportRules.php
  shoppingfeed.php
  translations/fr.php
  upgrade/install-2.0.0.php
Labels: enhancement

#392 Fix variation image without hierarchical (49175)
  controllers/front/product.php
Labels: bug

#388 Export product - fix images variation (49175)
  controllers/front/product.php
Labels: bug
