Repository shoppingflux/module-prestashop, pull requests merged in 2024-10, with the labels that each got.

#368 SyncAll execution precess compat PS 8+ (48174)
  controllers/front/syncAll.php
Labels: bug

#371 Add option in BO to enable/disable adding cdiscount fees (48305)
  shoppingfeed.php
  src/OrderImport/Rules/Cdiscount.php
  translations/fr.php
Labels: enhancement

#372 Do not look for a point id if an order comes from eBay (48460)
  src/OrderImport/Rules/ColissimoRule.php
Labels: bug

#374 Release 1.12.1
  202/build.xml
  202/docker/run_for_unittest.sh
  202/tests/OrderImport/OrderImportGroupCustomerTest.php
  202/tests/OrderImport/dataset/order-customer-group-2.json
  202/tests/OrderImport/dataset/order-customer-group-3.json
  202/tests/ProductSerializer/TestAttributeTestCase.php
  classes/ShoppingfeedApi.php
  classes/ShoppingfeedPreloading.php
  classes/ShoppingfeedToken.php
  classes/actions/ShoppingfeedOrderImportActions.php
  controllers/admin/AdminShoppingfeedOrderImportRules.php
  controllers/front/syncAll.php
  controllers/front/syncOrder.php
  shoppingfeed.php
  src/OrderImport/GLS/CartCarrierAssociation.php
  src/OrderImport/Rules/AmazonEbay.php
  src/OrderImport/Rules/Cdiscount.php
  src/OrderImport/Rules/ColissimoRule.php
  src/OrderImport/Rules/GroupCustomer.php
  src/OrderImport/Rules/ManomanoDpdRelais.php
  src/OrderImport/Rules/ShippedByMarketplace.php
  src/OrderImport/Rules/SkipTax.php
  src/OrderImport/Rules/TestingOrder.php
  src/Services/ProductAttributeCombination.php
  src/Services/ProductSerializer.php
  translations/fr.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_files.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  views/templates/admin/shoppingfeed_order_import_rules/order_status_syncro_178.tpl
Labels: release
