Repository shoppingflux/module-prestashop, pull requests merged in 2024-01, with the labels that each got.

#320 Fix Mondial Relay SOAP client domain (43708)
  src/OrderImport/Rules/AbstractMondialrelay.php
Labels: bug

#319 Add company name on colissimo address for ManoMano (43707)
  src/OrderImport/Rules/AbstractColissimo.php
  src/OrderImport/Rules/MonechelleColissimo.php
Labels: bug

#316 Fix cleaning of old task order status sync (42833)
  controllers/front/syncOrder.php
Labels: bug

#315 Creation of the order-carrier association if it it's need (43219)
  classes/actions/ShoppingfeedOrderImportActions.php
Labels: bug

#314 Update Header User-Agent for tracking (43218)
  src/Services/OrderTracker.php
Labels: enhancement

#323 Release 1.10.6
  202/build.xml
  classes/actions/ShoppingfeedOrderImportActions.php
  controllers/front/syncOrder.php
  src/OrderImport/Rules/AbstractColissimo.php
  src/OrderImport/Rules/AbstractMondialrelay.php
  src/OrderImport/Rules/MonechelleColissimo.php
  src/Services/OrderTracker.php
  vendor/prefixed/shoppingfeed/php-sdk/src/Http/Adapter/Guzzle6Adapter.php
Labels: release
