Repository shoppingflux/module-prestashop, pull requests merged in 2025-03, with the labels that each got.

#410 Redundant images in the catalog xml (50672)
  src/Services/ProductSerializer.php
Labels: bug

#415 refs #35363 translation
  controllers/admin/AdminShoppingfeedOrderImportRules.php
  translations/fr.php
Labels: enhancement

#417 refs #49022 update shoppingfeed php-sdk
  classes/ShoppingfeedApi.php
  classes/actions/ShoppingfeedOrderImportActions.php
  vendor/prefixed/shoppingfeed/php-sdk/src/Api/Order/Operation.php
Labels: enhancement

#411 refs #50671 redundant images in the catalog xml
  src/Services/ProductSerializer.php
Labels: bug

#414 Bugfix/50321 unit product price
  classes/actions/ShoppingfeedOrderImportActions.php
Labels: bug

#421 Fix hook method name (43794)
  202/build.xml
  shoppingfeed.php
Labels: bug

#422 Wording + translation (50400)
  controllers/admin/AdminShoppingfeedOrderImportRules.php
  translations/fr.php
Labels: enhancement

#423 refs #43794 block notification about an order status update
  shoppingfeed.php
Labels: enhancement

#424 🚀 Release 2.0.1
  202/build.xml
  controllers/admin/AdminShoppingfeedOrderImportRules.php
  shoppingfeed.php
  translations/fr.php
Labels: release

#407 refs #50284 typo in translation
  translations/fr.php
Labels: enhancement
